export const COMPONENT_LIST = [
  { icon: "⌨️", title: "Input" },
  { icon: "🎛️", title: "Switch" },
  { icon: "🖲️", title: "Button" },
  { icon: "📻", title: "Radio" },
  { icon: "☑️", title: "Checkbox" },
  { icon: "🎉", title: "Modal" },
  { icon: "📏", title: "Table" },
  { icon: "🃏", title: "Card" },
  { icon: "🗂", title: "Tabs" },
  { icon: "📛", title: "Badge" },
  { icon: "🎚", title: "Slider" },
  { icon: "⤵️", title: "Select" },
  { icon: "⏳", title: "Loading" },
  { icon: "🌠", title: "Icon" },
  { icon: "🛠", title: "Tooltip" },
  { icon: "🧭", title: "Navigation" },
  { icon: "🥐", title: "Breadcrumb" },
];
